services:
  - type: web
    name: herflows-api
    env: node
    rootDir: apps/api
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/main
    plan: free
